### PR TITLE
fix: exercise creation with static number field

### PR DESCRIPTION
**Pull request by maxinteger**
- use false for isDynamic for each field type by default
- convert number filed solution into string

issue: #608

### CODE REVIEW

**Comment by vektor8891** [comment]
@maxinteger I ran `npm install` and `npm start` (if I ran only the second, it failed to compile). Now the website is working but I get az 500 error:

```
HTTP/1.1 500 Internal Server Error
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 264
etag: W/"108-/zxdatNh4k047X9gyMHE6qRI+XA"
date: Wed, 09 Jun 2021 22:50:27 GMT
connection: keep-alive
keep-alive: timeout=5
```

**Comment by maxinteger** [comment]
@vektor8891 
> I ran npm install and npm start (if I ran only the second, it failed to compile).
this is normal, you should run `npm install` after changing branch or just run it before each `npm star`

> Now the website is working but when I want to save the exercise I get an 500 error:
I could not reproduce the 500 error. Please start the app again and then open http://localhost:4000/logs?q=metadata.emulator.name%3D%22functions%22 beside http://localhost:8080/ then try to save an exercise again. If you get the error again check the first page, you should see the details of the error.

**Comment by vektor8891** [comment]
@maxinteger I've tried to open the links you mentioned but I couldn't open the first:

kép

**Comment by vektor8891** [comment]
@maxinteger I've tried to run on the test server (after I deployed the changes to develop) but still couldn't save the exercise. I get a 400 error:

```
Állapot400
Bad Request
VerzióHTTP/2
Átküldve1,03 kB (4,63 kB méretű)
Hivatkozó házirendsame-origin
```

If I create a dynamic solution, it works. However, if I set it back to static, I cannot save it.

Here is the full response:
```

```

**Comment by maxinteger** [comment]
@vektor8891 
> after I deployed the changes to develop

Sorry but I do not understand what did you do.

also the quoted error message do not help, since it is just a number (400)  which could represent any kind of error. Did you get any response from the server (in devtools check the "Network" plan, select the failed request then select the "Response" tab)

**Comment by vektor8891** [comment]
@maxinteger 

> Sorry but I do not understand what did you do.

I ran the [Firebase Deploy](https://github.com/zsebtanar/zsebtanar-proto/actions/workflows/deploy.yml) workflow because I saw that the latest deployment happened 2 days before your [comment ](https://github.com/zsebtanar/zsebtanar-proto/pull/609#issuecomment-859911227).

This is the error I found in the "response" tab:

```
{"errors":{"body":[{"keyword":"const","dataPath":".subTasks[0].controls[0].type","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/0/properties/type/const","params":{"allowedValue":"binary-choice"},"message":"should be equal to constant"},{"keyword":"type","dataPath":".subTasks[0].controls[0].solution","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/0/then/properties/solution/type","params":{"type":"array"},"message":"should be array"},{"keyword":"if","dataPath":".subTasks[0].controls[0]","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/0/if","params":{"failingKeyword":"then"},"message":"should match \"then\" schema"},{"keyword":"const","dataPath":".subTasks[0].controls[0].type","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/1/properties/type/const","params":{"allowedValue":"fraction-number"},"message":"should be equal to constant"},{"keyword":"type","dataPath":".subTasks[0].controls[0].solution","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/1/then/properties/solution/type","params":{"type":"object"},"message":"should be object"},{"keyword":"if","dataPath":".subTasks[0].controls[0]","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/1/if","params":{"failingKeyword":"then"},"message":"should match \"then\" schema"},{"keyword":"const","dataPath":".subTasks[0].controls[0].type","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/2/properties/type/const","params":{"allowedValue":"multi-choice"},"message":"should be equal to constant"},{"keyword":"type","dataPath":".subTasks[0].controls[0].solution","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/2/then/properties/solution/type","params":{"type":"array"},"message":"should be array"},{"keyword":"if","dataPath":".subTasks[0].controls[0]","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/2/if","params":{"failingKeyword":"then"},"message":"should match \"then\" schema"},{"keyword":"const","dataPath":".subTasks[0].controls[0].type","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/3/properties/type/const","params":{"allowedValue":"number-list"},"message":"should be equal to constant"},{"keyword":"type","dataPath":".subTasks[0].controls[0].solution","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/3/then/properties/solution/type","params":{"type":"array"},"message":"should be array"},{"keyword":"if","dataPath":".subTasks[0].controls[0]","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/3/if","params":{"failingKeyword":"then"},"message":"should match \"then\" schema"},{"keyword":"const","dataPath":".subTasks[0].controls[0].type","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/4/properties/type/const","params":{"allowedValue":"simple-text"},"message":"should be equal to constant"},{"keyword":"type","dataPath":".subTasks[0].controls[0].solution","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/4/then/properties/solution/type","params":{"type":"array"},"message":"should be array"},{"keyword":"if","dataPath":".subTasks[0].controls[0]","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/4/if","params":{"failingKeyword":"then"},"message":"should match \"then\" schema"},{"keyword":"const","dataPath":".subTasks[0].controls[0].type","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/5/properties/type/const","params":{"allowedValue":"single-choice"},"message":"should be equal to constant"},{"keyword":"type","dataPath":".subTasks[0].controls[0].solution","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/5/then/properties/solution/type","params":{"type":"string"},"message":"should be string"},{"keyword":"if","dataPath":".subTasks[0].controls[0]","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/5/if","params":{"failingKeyword":"then"},"message":"should match \"then\" schema"},{"keyword":"type","dataPath":".subTasks[0].controls[0].solution","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/6/then/properties/solution/type","params":{"type":"string"},"message":"should be string"},{"keyword":"if","dataPath":".subTasks[0].controls[0]","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf/6/if","params":{"failingKeyword":"then"},"message":"should match \"then\" schema"},{"keyword":"anyOf","dataPath":".subTasks[0].controls[0]","schemaPath":"#/properties/subTasks/items/properties/controls/items/anyOf","params":{},"message":"should match some schema in anyOf"}]}}
```

**Comment by maxinteger** [comment]
@vektor8891 Sorry my bad. Currently we can not deploy feature branch to the test server :(

You have to test the fix locally. 
Or I can merge this and then deploy on test

**Comment by vektor8891** [comment]
@maxinteger In this case I suggest to merge the changes to develop. The issue on my end doesn't seem to be related to this.

**Pull request merged**
